<a href="https://colab.research.google.com/github/gtimokhina/homework_0-directory/blob/master/Basics_NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#The basics of NumPy Arrays

In [0]:
import numpy as np
np.random.seed(0)

In [2]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))
print(x1)
print(x2)
print(x3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [3]:
print(x3.ndim)
print(x3.shape)
print(x3.size)

3
(3, 4, 5)
60


In [4]:
print(x3.dtype)

int64


In [5]:
print(x3.itemsize)
print(x3.nbytes)

8
480


In [6]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [7]:
x2[0,0]

3

In [9]:
x2[0,-1]

4

In [0]:
x2[0,0] = 12

In [11]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [12]:
x2[0,0] = 3.5679 # will be truncated
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

#x[start:stop:step]

In [13]:
# slicing
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x[:5]

array([0, 1, 2, 3, 4])

In [15]:
x[5:]

array([5, 6, 7, 8, 9])

In [16]:
x[4:7]

array([4, 5, 6])

In [17]:
# every other el
x[::2]

array([0, 2, 4, 6, 8])

In [18]:
# every other el, starting at index 1
x[1::2]

array([1, 3, 5, 7, 9])

In [19]:
# all elements recersed
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [20]:
# reversed every other el from index 5
x[5::-2]

array([5, 3, 1])

#Multi-dimentional subarrays

In [21]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [22]:
x2[:2, :3] # 2 rows, 3 columns

array([[3, 5, 2],
       [7, 6, 8]])

In [23]:
x2[:3, ::2] # all rows , every other column

array([[3, 2],
       [7, 8],
       [1, 7]])

In [24]:
# reversed dimensions alltogether
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [25]:
x2[:, 0] # first column

array([3, 7, 1])

In [26]:
x2[0, :]

array([3, 5, 2, 4])

In [27]:
x2[0] # also first row, for convinience

array([3, 5, 2, 4])

# Slices of arrays return *views*

In [28]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [29]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[3 5]
 [7 6]]


In [30]:
# if modify subarray, the original array is changed
x2_sub[0,0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [31]:
print(x2) # x2 also changed

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [32]:
# copies of arrays
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [33]:
x2_sub_copy[0,0] = 77
print(x2_sub_copy)

[[77  5]
 [ 7  6]]


In [34]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [37]:
# reshaping
grid = np.arange(1, 10).reshape((3,3))  # 3x3 grid
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [39]:
x.reshape((1,3))  # row vector via reshape

array([[1, 2, 3]])

In [40]:
x[np.newaxis, :] # row vector via newaxis

array([[1, 2, 3]])

In [41]:
x.reshape((3,1)) # column vector reshape

array([[1],
       [2],
       [3]])

In [42]:
x[:, np.newaxis] # column vector via newaxis

array([[1],
       [2],
       [3]])

#Array Concatenation

In [43]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [45]:
z = [99,99,99]
print(np.concatenate([x,y,z]))

[ 1  2  3  4  5  6 99 99 99]


In [47]:
# 2 dimensional arrays
grid = np.array([[1,2,3],[4,5,6]])
print(grid)

[[1 2 3]
 [4 5 6]]


In [48]:
np.concatenate([grid, grid]) # along the first axis

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [49]:
np.concatenate([grid, grid], axis=1) # along the second axis

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [51]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],[6,5,4]])
print(x)
print(grid)

[1 2 3]
[[9 8 7]
 [6 5 4]]


In [52]:
# vertically stack
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [56]:
# horizontally stack
y = np.array([[99],[99]])
print(y)
np.hstack([grid, y])

[[99]
 [99]]


array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

# Splitting of arrays

In [57]:
x = [1, 2, 3, 77, 77, 5, 6, 7]
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)

[1 2 3] [77 77] [5 6 7]


In [59]:
# vertical split
grid = np.arange(16).reshape((4,4))
grid

upper, lower = np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [60]:
# horizontal split
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
