<a href="https://colab.research.google.com/github/gtimokhina/homework_0-directory/blob/master/Numpy_Einsum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#numpy.einsum practice

In [0]:
import numpy as np

In [5]:
a = np.arange(25).reshape(5,5)
b = np.arange(5)
c  = np.arange(6).reshape(2,3)
print('a:', a)
print('b:', b)
print('c:', c)

a: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
b: [0 1 2 3 4]
c: [[0 1 2]
 [3 4 5]]


###Trace of a matrix:

In [6]:
# number of elements in matrix
np.einsum('ii', a)

60

In [7]:
np.einsum(a, [0,0])

60

In [8]:
np.trace(a)

60

###Extract the diagonal(requires explicit form):

In [10]:
np.einsum('ii->i', a)

array([ 0,  6, 12, 18, 24])

In [11]:
np.einsum(a, [0,0], [0])

array([ 0,  6, 12, 18, 24])

In [12]:
np.diag(a)

array([ 0,  6, 12, 18, 24])

###Sum over an axis (requires explicit form):

In [13]:
np.einsum('ij->i',a)

array([ 10,  35,  60,  85, 110])

In [14]:
np.einsum(a, [0,1], [0])

array([ 10,  35,  60,  85, 110])

In [15]:
np.sum(a, axis=1)

array([ 10,  35,  60,  85, 110])

###Summing higher dimensional arrays using ellipsis:

In [16]:
np.einsum('...j->...', a)

array([ 10,  35,  60,  85, 110])

In [17]:
np.einsum(a, [Ellipsis,1], [Ellipsis])

array([ 10,  35,  60,  85, 110])

###Compute a matrix transpose, or reorder any number of axes:

In [18]:
np.einsum('ji', c)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [19]:
np.einsum('ij->ji', c)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [20]:
np.einsum(c, [1,0])

array([[0, 3],
       [1, 4],
       [2, 5]])

In [21]:
np.transpose(c)

array([[0, 3],
       [1, 4],
       [2, 5]])

###Vector inner product:

In [22]:
print(b)
np.einsum('i,i', b, b)

[0 1 2 3 4]


30

In [23]:
np.einsum(b, [0], b, [0])

30

In [24]:
np.inner(b,b)

30

###Matrix vector mulitiplication:

In [25]:
np.einsum('ij, j', a,b)

array([ 30,  80, 130, 180, 230])

In [26]:
np.einsum(a,[0,1], b, [1])

array([ 30,  80, 130, 180, 230])

In [27]:
np.dot(a,b)

array([ 30,  80, 130, 180, 230])

In [28]:
np.einsum('...j,j', a, b)

array([ 30,  80, 130, 180, 230])

###Broadcasting and scalar multipliction:

In [29]:
print(c)

[[0 1 2]
 [3 4 5]]


In [30]:
np.einsum('..., ...', 3, c)

array([[ 0,  3,  6],
       [ 9, 12, 15]])

In [31]:
np.einsum(',ij', 3, c)

array([[ 0,  3,  6],
       [ 9, 12, 15]])

In [32]:
np.einsum(3, [Ellipsis], c, [Ellipsis])

array([[ 0,  3,  6],
       [ 9, 12, 15]])

In [33]:
np.multiply(3, c)

array([[ 0,  3,  6],
       [ 9, 12, 15]])

###Vector outer product:

In [34]:
print(b)

[0 1 2 3 4]


In [35]:
np.einsum('i,j', np.arange(2) + 1, b)

array([[0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])

In [36]:
np.einsum(np.arange(2) + 1, [0], b, [1])

array([[0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])

In [37]:
np.outer(np.arange(2) + 1, b)

array([[0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8]])

###Tensor contraction:

In [38]:
a = np.arange(60).reshape(3,4,5)
print(a)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [39]:
b = np.arange(24).reshape(4,3,2)
print(b)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [40]:
np.einsum('ijk,jil->kl', a, b)

array([[4400, 4730],
       [4532, 4874],
       [4664, 5018],
       [4796, 5162],
       [4928, 5306]])

In [41]:
np.tensordot(a,b,axes=([1,0],[0,1]))

array([[4400, 4730],
       [4532, 4874],
       [4664, 5018],
       [4796, 5162],
       [4928, 5306]])

###Writeable returned arrays:

In [42]:
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [44]:
np.einsum('ii->i', a)[:] = 1 # make diagonal els = 1
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


###Example of ellipsis use:

In [46]:
a = np.arange(6).reshape((3,2))
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [47]:
b = np.arange(12).reshape((4,3))
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [48]:
np.einsum('ki,jk->ij', a, b)

array([[10, 28, 46, 64],
       [13, 40, 67, 94]])

In [49]:
np.einsum('ki,...k->i...', a, b)

array([[10, 28, 46, 64],
       [13, 40, 67, 94]])

In [50]:
np.einsum('k...,jk', a, b)

array([[10, 28, 46, 64],
       [13, 40, 67, 94]])

#Chained array operations:

In [52]:
a = np.ones(64).reshape(2,4,8)
print(a)

[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [0]:
for iteration in range(500):
  _ = np.einsum('ijk, ilm, njm,nlk,abc->', a,a,a,a,a)

In [0]:
for iteration in range(500):
  _ = np.einsum('ijk, ilm, njm,nlk,abc->', a,a,a,a,a, optimize='optimal')

In [0]:
for iteration in range(500):
  _ = np.einsum('ijk, ilm, njm,nlk,abc->', a,a,a,a,a, optimize='greedy')

In [0]:
path = np.einsum_path('ijk,ilm,njm,nlk,abc->',a,a,a,a,a, optimize='optimal')[0]
for iteration in range(500):
    _ = np.einsum('ijk,ilm,njm,nlk,abc->',a,a,a,a,a, optimize=path)